# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo "Fetching AWS Account ID..."
#       - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
#       - echo Logging in to Amazon ECR...
#       - echo $AWS_DEFAULT_REGION
#       - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
#       - echo $REPOSITORY_URI
#       - aws --version
#       - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
#       - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/gsa-comet-prod-spring-backend
#       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
#       - IMAGE_TAG=${COMMIT_HASH:=latest}
#   build:
#     commands:
#       - echo Build started on `date`
#       - mvn package -Dmaven.test.skip=true
#       - echo Building the Docker image...
#       - docker build -t $REPOSITORY_URI:latest .
#       - echo Tagging Docker image...
#       - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Pushing the Docker images...
#       - docker push $REPOSITORY_URI:$IMAGE_TAG
# artifacts:
#   files:
#     - appspec.yml
#     - scripts/* 

version: 0.2

phases:
  pre_build:
    commands:
      - echo "Fetching AWS Account ID..."
      - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $REPOSITORY_URI
      - aws --version
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
      - REPOSITORY_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/gsa-comet-prod-spring-backend"

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn package -Dmaven.test.skip=true
      - echo "Building Docker image with :latest tag..."
      - docker build -t "$REPOSITORY_URI:latest" .

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing the Docker image with :latest tag..."
      - docker push "$REPOSITORY_URI:latest"

artifacts:
  files:
    - appspec.yml
    - scripts/*
